# Generated by Django 3.1.7 on 2021-03-18 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'verbose_name': 'レシピ', 'verbose_name_plural': 'レシピ'},
        ),
        migrations.AlterField(
            model_name='recipe',
            name='content',
            field=models.TextField(verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='title',
            field=models.CharField(max_length=200, verbose_name='タイトル'),
        ),
    ]
